controllers:
    resource: ../../src/Controller/
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api/v2

admin_controllers:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
